## Piotr Rzeźnik


### Zadania


Zadanie 1 (1pkt)
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x. Nastepnie rozwiąż równanie Ax=b trzema metodami:

 - inv()
 - \
 - factorize()
 
Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy od drugiego wywołania !



In [2]:
using(LinearAlgebra)


In [34]:
function f(A, b)
    Af=factorize(A)
    return Af\b
    
end

f (generic function with 1 method)

In [40]:
using DataFrames
using Statistics
df = DataFrame(label=[], time=[], avg_delta=[])

M = 10

x = rand(1000)
A = rand(1000, 1000)
b = A*x


x1 = inv(A)*b

x1 = A\b

x1 =  f(A, b)



for k=1:M
    
    x = rand(1000)
    A = rand(1000, 1000)
    b = A*x
    
    t = @elapsed begin
        x1 = inv(A)*b
    end
    print(t)
    avg = mean(x-x1)
    insert!.(eachcol(df), 1,["inv", t, avg])
    
    t = @elapsed begin 
        x1 = A\b
    end
    avg = mean(x-x1)
    
    insert!.(eachcol(df), 1, ["\\", t, avg])
    
    t = @elapsed begin 
        x1 =  f(A, b)
    end
    avg = mean(x-x1)
    
    insert!.(eachcol(df), 1,["factorize", t, avg])
    
end

0.03471080.03556630.03443730.03873990.03527930.0346290.03486010.04022350.03424820.0347112

In [41]:
df

30×3 DataFrame
 Row │ label      time       avg_delta    
     │ Any        Any        Any          
─────┼────────────────────────────────────
   1 │ factorize  0.0140046  5.46146e-16
   2 │ \\         0.0128283  5.46146e-16
   3 │ inv        0.0347112  7.01919e-14
   4 │ factorize  0.0129501  -9.62875e-17
   5 │ \\         0.0143427  -9.62875e-17
   6 │ inv        0.0342482  -1.39283e-13
   7 │ factorize  0.0155366  -2.49222e-15
   8 │ \\         0.0143966  -2.49222e-15
   9 │ inv        0.0402235  8.95808e-14
  10 │ factorize  0.0130756  1.32279e-16
  11 │ \\         0.0148778  1.32279e-16
  ⋮  │     ⋮          ⋮           ⋮
  21 │ inv        0.0387399  1.81311e-14
  22 │ factorize  0.0147344  2.12163e-16
  23 │ \\         0.0153756  2.12163e-16
  24 │ inv        0.0344373  -5.05596e-16
  25 │ factorize  0.0198915  -1.39132e-16
  26 │ \\         0.0128105  -1.39132e-16
  27 │ inv        0.0355663  1.15721e-13
  28 │ factorize  0.0128005  -8.11213e-17
  29 │ \\         0.0128104  -8.11213e-17
  30 │ inv        0.0347108  6.79501e-15
                            9 rows omitted

In [44]:
ndf = DataFrame()
gdf1 = groupby(df, :label)
for i in 1:3
    row = combine(gdf1[i],"label", "time" => mean)
    push!(ndf, row[1,:])

end
ndf

3×2 DataFrame
 Row │ label      time_mean 
     │ String     Float64   
─────┼──────────────────────
   1 │ factorize  0.0149937
   2 │ \\         0.0139441
   3 │ inv        0.0357406

Zadanie 2 (1pkt)
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda z użyciem faktoryzacji QR zaprezentowana na tym laboratorium). Porównaj wyniki z tymi otrzymanymi poprzednio.



Zadanie 3 (2 pkt)
Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

zastosowanie faktoryzacji SVD

In [91]:
A=rand(5,4)

5×4 Array{Float64,2}:
 0.566689   0.803749  0.55968   0.161464
 0.20155    0.677637  0.161888  0.321054
 0.668205   0.983361  0.362124  0.412651
 0.0910576  0.525263  0.453084  0.574296
 0.618703   0.225025  0.328385  0.167764

In [92]:
rank(A)

4

In [93]:
F = qr(A)

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
5×5 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.517456   -0.151885   0.347094   0.765617   0.0502731
 -0.18404    -0.529492  -0.350223  -0.119302   0.740863
 -0.610153   -0.222334  -0.46547   -0.208429  -0.564072
 -0.0831466  -0.505145   0.708765  -0.469699  -0.122266
 -0.564951    0.626071   0.194575  -0.368155   0.339806
R factor:
4×4 Array{Float64,2}:
 -1.09514  -1.31142   -0.763548  -0.536946
  0.0      -0.823967  -0.274518  -0.471337
  0.0       0.0        0.354032   0.19121
  0.0       0.0        0.0       -0.3322

In [94]:
Q = F.Q
R = F.R;

In [95]:
R1 = inv(R)

4×4 Array{Float64,2}:
 -0.913121   1.45332  -0.842437  -1.071
  0.0       -1.21364  -0.941063   1.18029
  0.0        0.0       2.8246     1.6258
  0.0        0.0       0.0       -3.01023

In [96]:
A1 = [R1 zeros(4,1)] * Q

4×5 Array{Float64,2}:
  0.808097   0.0974814  -1.19288   -0.193849   1.63694
  0.699413   0.255625    1.69963   -0.213447  -0.512625
 -1.85862   -1.44927    -0.162455  -1.35237   -1.79206
  0.25029    1.5206     -2.13355    1.4139     0.36805

In [97]:
A1*A

4×4 Array{Float64,2}:
  0.675629  -0.190936    0.485804  -0.167174
  1.24697    2.17925     0.783259   0.687772
 -2.68581   -3.7493     -2.5349    -1.90973
 -0.620873  -0.0409674   0.375121   0.521943